version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    image: ${DOCKER_REGISTRY-}productmicroservice
    container_name: productmicroservice
    ports:
      - "5040:80"
    volumes:
      - ./src/data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped



