version: '3.8'

services:
  productapi:
    image: productmicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./logs:/app/logs

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: dotnet test --logger:trx
    volumes:
      - ./TestResults:/src/TestResults
